### ISSUE TITLE
Cannot create composite servers

### ISSUE THREAD

**Issue by mimihalescu** [ionos-cloud/sdk-java#1]
---
|  name |  about |   labels |  assignees |  
|---|---|---|---|
| Bug report  |  Creating composite servers |  bug |  mihaela-mh |  
---

## Description
Cannot create composite servers (a server that has nics/cdroms/volumes attached).

## Expected behavior
When trying to [create a server](https://github.com/ionos-cloud/sdk-java/blob/master/DOCS.md#datacentersServersPost) that has any entities attached, the operation should succeed.

## Environment

Java version: 1.11
```
```
SDK version: 5.0.0
```
```
OS: `Ubuntu 20.04`
```
```

## Configuration Files
N/A

## Error and Debug Output
The SDK returns NullPointerException when calling the datacentersServersPost method.

**Comment by mimihalescu** [comment]
I am currently working on it.
In the [Cloud API swagger file](https://api.ionos.com/cloudapi/v5/swagger.json) the AttachedVolumes, Cdroms and Nics `items` property is read-only, which means that when the Java SDK is generated, it does not generate setters for the `items` field. To solve this problem, I opened a PR for the swagger file to make the specified parameters editable.
The next step is to regenerate the SDK and release a new version of it.

**Comment by TomaAlexandru** [comment]
new sdk has been generated and published.
