### ISSUE TITLE
add ignores for Eclipse

### ISSUE THREAD

**Issue by AndreSchulz-IONOS** [ionos-cloud/sdk-java#3]
### Current SDK Version
• 5.0.1
• 6.0.0-SNAPSHOT

### Use-cases
Adding project to Eclipse results in changes

### Proposal
extend `.gitignore` with
```
/.settings/
/.classpath
/.project
```

**Comment by cristiGuranIonos** [comment]
I think this is solved. Please re-open if there's something else to add.
